# Generated by Django 4.2.3 on 2023-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webkiosk", "0002_food_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="customer", new_name="customers",
        ),
        migrations.RenameField(
            model_name="order", old_name="orderdatetime", new_name="orderDateTime",
        ),
        migrations.RemoveField(model_name="order", name="paymentmode",),
        migrations.AddField(
            model_name="order",
            name="paymentMode",
            field=models.CharField(
                choices=[("CH", "Cash"), ("CD", "Card"), ("DW", "Digital Wallet")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
